### ISSUE TITLE
[Tracking] Create documentation for the cmdlets Authentication module

### ISSUE THREAD

**Issue by maisarissi** [microsoftgraph/msgraph-sdk-powershell#1088]
We need to provide better documentation for the cmdlets we have in the Authentication module.
Today the only information we provide lives in the [README.md](https://github.com/microsoftgraph/msgraph-sdk-powershell#microsoft-graph-powershell-sdk), in the [app-only authentication](https://docs.microsoft.com/en-us/graph/powershell/app-only?view=graph-rest-1.0&tabs=azure-portal) and there are a few more in [this PR](https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/425).

There is no centralized information for the Authentication module and its cmdlets.

The goal is to [add missing cmdlets/information](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1088#issuecomment-1039510734) in the [PowerShell Browser documentation](https://docs.microsoft.com/en-us/powershell/microsoftgraph/app-only?view=graph-powershell-1.0&tabs=azure-portal) and link it in the Graph docs site. Which means the content will live in one place, facilitating maintenance, but it will be discoverable in various places.

For existing content as [Find-MgGraphCommand](https://docs.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-command?view=graph-powershell-1.0) and [Find-MgGraphPermission](https://docs.microsoft.com/en-us/powershell/microsoftgraph/find-mg-graph-permission?view=graph-powershell-1.0), it should be possible to type and be redirect to the Powershell online docs when:
```powershell
Get-Help Find-MgGraphCommand -Online
```
or
```powershell
Get-Help Find-MgGraphPermission -Online
```
instead of getting an error:
```powershell
Get-Help: The online version of this Help topic cannot be displayed because the Internet address (URI) of the Help topic is not specified in the command code or in the help file for the command.
```

After creating the content for the authentication module, it should also be possible to Get-Help online for each of the cmdlets. As an example:

```powershell
Get-Help Connect-MgGraph -Online
```
and be redirect to the Graph PowerShell docs.

Tasks
============================================================================

- [x] #1411
- [x] #1412
- [x] #1413

**Comment by maisarissi** [comment]
Hi @lramosvea @jasonjoh 
Can you help us here? How do we manage the content creation? We should use the PowerShell Browser docs as the source of truth and link it to the Graph docs site.
The reason why browser docs should be the main source is because when you type Get-Help <cmdlet> -Online in PowerShell, you will be redirect to that docs page.
As you can see, we already replicate the content that exists in the Graph docs site in the browser documentation thanks to @msewaweru . 
Now we need to have a plan to better suit what we need for the missing information.

What we need document are the following:
```powershell
Connect-Graph
```
```powershell
Disconnect-Graph
```
```powershell
Get-MgContext
```
```powershell
Get-MgProfile
```
```powershell
Select-MgProfile
```
```powershell
Invoke-GraphRequest
```
```powershell
Add-MgEnvironment
```
```powershell
Get-MgEnviroment
```
```powershell
Remove-MgEnviroment
```
```powershell
Set-MgEnviroment
```

**Comment by lramosvea** [comment]
Hi @maisarissi, so you will be adding a new element to the PowerShell browser docs under Reference, which will be called Microsoft.Graph.Authentication with the info on all these cmdlets, correct?

Then, will you need to update only [this existing page?](https://docs.microsoft.com/en-us/graph/powershell/app-only?view=graph-rest-1.0&tabs=azure-portal) with the new info on these cmdlets or do you want to create a new page?

**Comment by maisarissi** [comment]
Hi @lramosvea . That's a good question.

I believe there is no way for us to create a new reference page called Microsoft.Graph.Authentication.
Our reference documentation is created by an automated process using the AutoREST.PowerShell tool. If we create a new page manually, this will be overridden in the next run.

@georgend can we investigate whether is it possible to add the Microsoft.Graph.Authentication module to the docs generation?

**Comment by peombwa** [comment]
As part of this task, we should add links to various online reference docs for relevant parameters. e.g., `Connect-MgGraph -Scope` should have a link to https://docs.microsoft.com/en-us/graph/permissions-reference in its description.

**Comment by maisarissi** [comment]
- [ ] Conceptual documentation around Authentication module
- [ ] Add support in the Graph PS SDK to generate a new node in the reference documentation following the same pattern we have for all other modules
- [ ] Link Get-Help for each cmdlet to their respective content page in PowerShell docs.

**Comment by msewaweru** [comment]
@maisarissi, I think we can now close this after the conclusion of the work [here](https://learn.microsoft.com/en-us/powershell/microsoftgraph/authentication-commands?view=graph-powershell-1.0).
