### ISSUE TITLE
[Tracking] Split the SDK Beta and V1 versions

### ISSUE THREAD

**Issue by ddyett** [microsoftgraph/msgraph-sdk-powershell#837]
[AB#10963](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10963)

Tasks to be completed as part of this item:
- [x] https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1228.
- [x] https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/692#issue-916683722.
- [x] https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1069
- [x] https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1295
- [x] https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/838.
- [x] #1296
- [x] #1431

**Comment by peombwa** [comment]
Tasks to be completed as part of this item:
- [ ] Share design spec for the new SDK structure.
- [ ] Review current module mapping.
- [ ] Split SDK into v1.0 and beta - https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/692#issue-916683722.
- [ ] Move directives to each service version module i.e., Current `Microsoft.Graph.Groups` directives should be moved to `Microsoft.Graph.Groups` and `Microsoft.Graph.Beta.Groups` accordingly.
- [ ] Move custom commands to each service version module.
- [ ] Add basic conformance tests for each module. See [Sites module tests](https://github.com/microsoftgraph/msgraph-sdk-powershell/blob/dev/src/Sites/Sites/test/v1.0-beta/Get-MgSite.Tests.ps1) for inspiration.
